import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(("127.0.0.1", 5089))  # слушаем только localhost
s.listen(10)

print("Server started")

conn, addr = s.accept()
print("KUMALALALALALLAALALALALAALALALALALAL:", addr)

conn.sendall(b"Hello KUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALALKUMALALALALALLAALALALALAALALALALALAL! \n")

conn.close()
s.close()